name: flutter_app 
description: A Flutter hello world project.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
