name: flutter_app 
description: A Flutter hello world project.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  flutter_rust_bridge: 2.10.0

flutter:
  uses-material-design: true
  # assets:
  #   - asset_manifest.drift
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
