# .github/workflows/check.yml
name: Code Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter-check:
    name: Flutter Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: ./flutter_app
      - name: Analyze Flutter code
        run: flutter analyze
        working-directory: ./flutter_app

  rust-check:
    name: Rust Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Check Rust with Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Audit for security vulnerabilities # <-- ADDED
        run: |
          cargo install cargo-audit
          cargo audit